version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: aguinto/cs608:latest
    steps:
      - checkout
      - run: mkdir build && cd build && cmake .. && make -j4
  test:
    docker:
      - image: aguinto/cs608:latest
    steps:
      - checkout
      - run: ./build/test/run_tests

# Orchestrate our job run sequence
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test