version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_and_test:
    docker:
      - image: "aguinto/cs608:latest"
    steps:
      - checkout
      - run: |
          mkdir build && cd build && cmake .. && make -j4 && /bin/bash test/run_tests
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_and_test
